name: 02-Deployment-API

on:
  push:
    paths:
      - 'src/github-app/**'
  workflow_dispatch:

env:
  CONFIGURATION: 'release'
  APP_NAME: 'app-githubdashboard'
  CSPROJ: 'src/github-dashboard.api/github-dashboard.api.csproj'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      
      - name: Restore dependencies
        run: dotnet restore ${{ env.CSPROJ }}
      
      - name: Build
        run: dotnet build ${{ env.CSPROJ }} --configuration ${{ env.CONFIGURATION }} --no-restore
        
      - name: Publish
        run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output MyPublishApp ${{ env.CSPROJ }}
      
      - name: Upload dotnet publish results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish
          path: MyPublishApp
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dotnet-publish
          path: my-app-artifact
      
      - name: Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZ_CREDENTIALS }}

      - uses: azure/webapps-deploy@v3
        name: Deploy to Azure
        with:
          app-name: ${{ env.APP_NAME }}
          package: my-app-artifact
